# nixpacks.toml

[phases.setup]
# instala Node 20 + npm 10 + openssl
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma migrate deploy && node dist/main.js"
