[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[variables]
NPM_CONFIG_CACHE = "/tmp/npm-cache"

[phases.install]
# instala deps (executa postinstall -> prisma generate)
cmds = ["npm ci"]

[phases.build]
# garante novamente a geração antes do build (idempotente e rápido)
cmds = [
  "npm run prisma:generate",
  "npm run build"
]

[start]
# se quiser aplicar migrações automaticamente:
# cmd = "npm run prisma:deploy && npm run start"
cmd = "npm run start"
