# nixpacks.toml
[phases.setup]
# se precisar de pacotes do SO, pode listar aqui (ex.: openssl)
# nixPkgs = ["openssl"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma migrate deploy && node dist/main.js"
